### ISSUE TITLE
Add the ability to use the warninglists to filter out false positives

### ISSUE THREAD

**Issue by iglocska** [MISP/mail_to_misp#1]
Would be handy to have the filtering already enforced on import.

**Comment by adulau** [comment]
@iglocska When opening an issue, we recommend to add a description ;-)

**Comment by iglocska** [comment]
What do you mean, it's there?

**Comment by rommelfs** [comment]
That's in relation with the (outstanding) PyMISP upgrade using the freetext import of MISP directly. The idea is to make it configurable so either the parsing is done by
a) MISP (full benefit of freetext import parser)
or
b) mail_to_misp (more configurable granularity on how to deal with different types)

In case of a) your proposal will be taken into account and discussed with the MISP lead development team.

**Comment by adulau** [comment]
Maybe we should have a generic Python library for [misp-warninglists](https://github.com/MISP/misp-warninglists) to filter out from any datastream? @Rafiot a good challenge?

**Comment by Rafiot** [comment]
I did this one: https://github.com/MISP/PyMISPWarningLists 
I still need to figure out a simple way to search in the lists in a more clever way (i.e. cidr blocks) but it is an option already.

**Comment by Rafiot** [comment]
Done.

**Comment by obsidianpentesting** [comment]
Hey guys, I love what you've done with mail_to_misp. Is this feature currently implemented or in the works? Otherwise, I may be able to help add the API call before these attributes are imported.

**Comment by rommelfs** [comment]
Hi @obsidianpentesting, thank you for your words!

Locally it would be already working, but we are working on a solution using the server's warning list + pymisp.  It should come in the following days (hopefully).

**Comment by rommelfs** [comment]
Hi @obsidianpentesting and others,

with the latest version, you can configure:
`enforcewarninglist=True` 

This will look up if a to-be-added attribute is on a server side warning list. If yes, the creation is skipped.

Be sure to implement the following in your config file, it won't be added automatically (mail_to_misp_config.py):
`# Ignore (don't add) attributes that are on server side warning list
enforcewarninglist=True`

Thanks @Rafiot and @iglocska for the work you've done on your parts 👍

**Comment by Rafiot** [comment]
It is the best kind of fixes, I didn't have to do anything \o/

**Comment by obsidianpentesting** [comment]
Very nice! So easy to implement.
