### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/mail_to_misp#14]
Add options to auto publish based on text found or tags applied. 

Add option to store attachments as Support tool attributes or External analysis attributes. This is for forwarding blog or intelligence emails to MISP and having the attachments be viewable. (not malicious)

**Comment by rommelfs** [comment]
auto publish is now possible via a configurable key you specify in the configuration.
m2m_key: specifies your secret key
m2m_auto_distribution: specifies your distribution override
Usually, m2m events are org only. If the configured key is matched as key:yourkey in the body of the forwarded mail, the distribution is changed to  the value in m2m_auto_distribution and the event is published.

**Comment by rommelfs** [comment]
The second feature request is implemented as well.
Configure m2m_attachment_keyword and use it in the body of the mail to specify that an attachment is benign.
Example:
m2m_attachment_keyword  = attachment:benign

Write in the forwarded message:
attachment:benign

That should do the trick.

Let me know if that's what you had in mind.
