### ISSUE TITLE
Permission of execution under postfix in Ubuntu

### ISSUE THREAD

**Issue by makakin** [MISP/mail_to_misp#15]
Hi all,

The script cannot execute after I create the aliases, when I type mailq the message showed as below: 
(temporary failure. Command output: local: fatal: execvp /home/cisp/mail_to_misp/mail_to_misp.py: Permission denied)

Thanks a lot.

**Comment by rommelfs** [comment]
What are the permissions of /home/cisp/mail_to_misp/mail_to_misp.py?

**Comment by makakin** [comment]
root:root

**Comment by rommelfs** [comment]
Is python installed? What does /usr/bin/env python3 -V output when run as the user running the script?
Is the directory accessible by the user running the script?

**Comment by makakin** [comment]
Oh, the directory may be restricted by the www-data user only

# /usr/bin/env python3 -V
Python 3.5.2

# ./mail_to_misp.py "test"
INFO [api.py:81 - __init__() ] To configure logging in your script, leave it to None and use the following: import logging; logging.getLogger('pymisp').setLevel(logging.DEBUG)
DEBUG [api.py:138 - __prepare_request() ] GET - https://myserver.com/servers/getPyMISPVersion.json
DEBUG [api.py:156 - __prepare_request() ] {'Connection': 'keep-alive', 'Authorization': '%9$JTG6Wm959d9fPUj3sh*uGa^3R5f3mStKkU%usQcxgAr#@', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'content-type': 'application/json', 'User-Agent': 'PyMISP 2.4.87.1 - Python 3.5.2'}
DEBUG [api.py:244 - _check_response() ] {
    "version": "2.4.89"
}
WARNING [api.py:96 - __init__() ] The version of PyMISP recommended by the MISP instance (2.4.89) is newer than the one you're using now (2.4.87.1). Please upgrade PyMISP.
...
