### ISSUE TITLE
Email Subject Prefix issue

### ISSUE THREAD

**Issue by makakin** [MISP/mail_to_misp#19]
I tried to enable the option [email_subject_prefix = b'M2M - '], however, the subject doesn't show the M2M - prefix in front of the title.

**Comment by rommelfs** [comment]
Hi!

That's true, there was a bug in the previous version not handling this correctly.

The very new refactored version should take care of this again properly. git pull, have fun.

**Comment by makakin** [comment]
I got this error in my email log

(Command died with status 1: "/mail_to_misp.py". Command output:   File "/mail_to_misp.py", line 55     self.misp_event.info = f'{config.email_subject_prefix} - {self.subject}'                                                                            ^ SyntaxError: invalid syntax )

**Comment by rommelfs** [comment]
That is due to the new requirement python3.6. Can you meet that in your installation?
Otherwise I could give you a quick fix for the version of mail_to_misp you are running, but that won't be supported after all and you should strongly consider the upgrade.

**Comment by makakin** [comment]
Oh, I will try to update 3.6 later, thanks!
