### ISSUE TITLE
DNS enrichment of hostnames

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/mail_to_misp#26]
Need the ability to disable the DNS lookups besides commenting out that section of the main script.

**Comment by robertnixon2003** [comment]
Where is the config would I set HAS_DNS = False? Just put it somewhere?

**Comment by Rafiot** [comment]
I forgot to update the sample config file, here it is: https://github.com/MISP/mail_to_misp/commit/145930d55d2b22b04ff64634613f921e931dcecd
