### ISSUE TITLE
Script is ignoring publish and attachment keys

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/mail_to_misp#28]
Both publish and attachment keys are in the email body but the events are not published and the attachments are still considered malicious.

**Comment by Rafiot** [comment]
Is the m2mkey also present? 
`m2m:m2mkey:YOUSETYOURKEYHERE` 

This one is required for autopublish.

**Comment by robertnixon2003** [comment]
Does it need the m2m prefix in the email body? I thought it was just looking for the string.

**Comment by Rafiot** [comment]
Yes, sorry, it wasn't clear at all in the documentation.

I updated the readme: https://github.com/MISP/mail_to_misp#pass-parameters-in-the-email-boddy

**Comment by robertnixon2003** [comment]
Gotcha. I have Splunk alerts sending emails to this. I will update the body of the email that Splunk send and close this if it works.

**Comment by Rafiot** [comment]
In your case, you need to have the following string in the body of the email:

`m2m:attachment:AttachmentSafe`

**Comment by robertnixon2003** [comment]
Tried that as well. Same thing. Also the auto publish is not working when used as stated.

**Comment by Rafiot** [comment]
This is weird, because this test case (passing) is testing exactly that: https://github.com/MISP/mail_to_misp/blob/master/tests/tests.py#L63

**Comment by robertnixon2003** [comment]
Okay it did not like the capital letter. Went all lower case and it did the attachment right. 
Also the auto publish is working but only if I add it by itself. I cannot add the distro, threat level, or analysis parameters. If I do the event will not show up in MISP. Just drops it somewhere.

**Comment by robertnixon2003** [comment]
!!!
It only will auto publish if the email is sent in plain text. HTML emails do not work.

**Comment by robertnixon2003** [comment]
Also my sighting are not populating. I noticed that I can only add sightings to events after I publish them. Also the enforcewarninglist does not work. It just added an IP that is on a warning list.

**Comment by Rafiot** [comment]
The parameters you send to the script *have to be* in a plain text mail body, parsing HTML to extract them may be implemented in the future, but doesn't have a particularly high priority.

I'll investigate the other issues later/tomorrow.

**Comment by Rafiot** [comment]
* I fixed one problem with distribution, threat_level and analysis (0 wasn't allowed). 
* Sightings are now properly added 
* Not sure which key/parameter you were talking about regarding the case issue.
* Enforce warning list requires a patch in MISP core
