### ISSUE TITLE
Numerous processing issues

### ISSUE THREAD

**Issue by jwilczek** [MISP/mail_to_misp#29]
When sending IOCs to mail_to_misp, I'm seeing numerous issues. I've tried IPs, domain names, URLs, and combinations of each.

If I just have a domain  name in the body, I get the following error:

`
Traceback (most recent call last):   File
    "/usr/local/src/mail_to_misp/mail_to_misp.py", line 67, in <module>
    mail2misp.process_body_iocs()   File
    "/usr/local/src/mail_to_misp/mail2misp/mail2misp.py", line 231, in
    process_body_iocs     domainname = self.f.get_domain().decode()
    AttributeError: 'str' object has no attribute 'decode'
`

**Comment by Rafiot** [comment]
Woops, never mind, pyfaup changed and they decode directly on their side. Fixing it now.

**Comment by jwilczek** [comment]
Yeah, I'm using Python 3.6 in a virtual environment. 

I'll test this later to confirm it worked.

Thanks!
