### ISSUE TITLE
OSError [Errno 98] Address already in use

### ISSUE THREAD

**Issue by mbunde** [MISP/mail_to_misp#30]
I have  just started with MISP virtual machine, when i run **sudo -u www-data misp-modules**  command  I get an error OSError [Errno 98] Address already in use. The error is in bind_sockets sock.bind(sockaddr).
Any help with this will be greatly apprciated.

**Comment by rommelfs** [comment]
Hi, 

I guess you want to open an issue for MISP/MISP. This is MISP/mail_to_misp.

Cheers
