### ISSUE TITLE
Fake SMTP Arguments

### ISSUE THREAD

**Issue by phpsystems** [MISP/mail_to_misp#47]
The Arguments for Fake SMTP seem to have been cut and pasted:

    parser.add_argument("--path", default='./mail_to_misp.py', help="Path to the mail_to_misp.py script.")
    parser.add_argument("--path_forward", default='./mail_to_misp.py', help="Path to the mail_to_misp.py script.")
    parser.add_argument("--email_forward", default='mail2misp@example.com', help="Path to the mail_to_misp.py script.")

At least 2 should be modified to be a bit clearer.

**Comment by SteveClement** [comment]
If you have more details on what you think should be cleared up, let me know and I change it.

**Comment by phpsystems** [comment]
Hang on, so what is the difference between path and path_forward?
