### ISSUE TITLE
M2M parsing of [@]

### ISSUE THREAD

**Issue by carnak** [MISP/mail_to_misp#6]
Hello!

I have just installed the latest version of M2M, and am overjoyed at how well it is working!

Thanks!  :)

That being said, there is a minor parsing issue we would like to request be considered, i.e., when we have a "defanged" email address that has a square bracket enclosing the @ sign, e.g., foo[@]bar.com, the email address does not get properly parsed out.

Best Regards,
Alan

**Comment by rommelfs** [comment]
Hi @carnak,

Sorry for having missed your issue for such a long time and thanks for enjoying M2M :) 

The refanging is done in an external module, you could patch defang/defang/init.py and add dirty_line = dirty_line.replace('[@]', '@') at line 47.

Does that make sense and work for you?

Cheers,
Sascha

**Comment by carnak** [comment]
Hello Sascha, and no worries, as the timing of your response is perfect 

I will implement the change you suggest shortly, and have response to you by Monday 

Have a great weekend!

Thanks!
Alan
