### ISSUE TITLE
No module named 'fake_smtp_config'

### ISSUE THREAD

**Issue by arnydo** [MISP/mail_to_misp#7]
Mail_to_misp is up and running but when trying to launch fake_smtp.py I receive the following:

> No module named 'fake_smtp_config'

Configs appear to be fine.

Any ideas?

**Comment by rommelfs** [comment]
Ok I see: fake_smtp_config.py should be a symlink to mail_to_misp_config.py.
This should fix it:
ln -s  mail_to_misp_config.py fake_smtp_config.py

I'll fix that in the documentation
