### ISSUE TITLE
Error with OSError: libfaupl.so.1: cannot open shared object file: No such file or directory )

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/mail_to_misp#8]
Please see my error below:

status=bounced (Command died with status 1: "/home/rnixon/mail_to_misp/mail_to_misp.py". Command output: Traceback (most recent call last):   File "/home/rnixon/mail_to_misp/mail_to_misp.py", line 15, in <module>     from pyfaup.faup import Faup   File "<frozen importlib._bootstrap>", line 969, in _find_and_load   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible   File "/usr/local/lib/python3.5/dist-packages/pyfaup-1.0-py3.5.egg/pyfaup/__init__.py", line 20, in <module>   File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary     return self._dlltype(name)   File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__     self._handle = _dlopen(self._name, mode) OSError: libfaupl.so.1: cannot open shared object file: No such file or directory )

**Comment by rommelfs** [comment]
Your faup installation doesn't seem to be working fine. Are you sure it is properly installed?

**Comment by robertnixon2003** [comment]
I fixed it. Apparently I had like 4 versions of python running on this machine.

**Comment by infosec-intern** [comment]
I just had this happen when using pipenv to install dependencies. According to [this](https://github.com/stricaud/faup/blob/master/README.md#why-do-i-receive-the-error-libfauplso1-cannot-open-shared-object-file-when-trying-to-run-faup) the default installation directory for libfaup is not in the default pipenv path. I was able to fix it by following the instructions on that page and reloading the pipenv
```bash
echo '/usr/local/lib' | sudo tee -a /etc/ld.so.conf.d/faup.conf
```
Just in case anyone else runs into the same issue with pipenv
