### ISSUE TITLE
fresh M2M install - KeyError: 'id'

### ISSUE THREAD

**Issue by carnak** [MISP/mail_to_misp#9]
I have now seen this same error on two separate fresh installs - any clue as to how to address?

Sep 28 14:23:08 misp3 postfix/local[51141]: A64D481ACB: to=<misp_handler@<redact.com>, relay=local, delay=1.3, delays=0.33/0/0/0.94, dsn=5.3.0, status=bounced (Command died with status 1: "/usr/src/mail_to_misp/mail_to_misp.py". Command output: /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning) Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header. /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning) /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning) /usr/local/lib/python3.5/dist-packages/pymisp-2.4.80-py3.5.egg/pymisp/api.py:1636: DeprecationWarning: Call to deprecated function add_tag.   def add_tag(self, event, tag, attribute=False): Traceback (most recent call last):   File "/usr/src/mail_to_misp/mail_to_misp.py", line 168, in <module>     misp.add_tag(new_event, tlp_tag)   File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.80-py3.5.egg/pymisp/api.py", line 69, in new_func     return func(*args, **kwargs)   File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.80-py3.5.egg/pymisp/api.py", line 1645, in add_tag     to_post = {'request': {'Event': {'id': event['id'], 'tag': tag}}} KeyError: 'id' )

**Comment by rommelfs** [comment]
I could imagine that this part of the error message is the cause of the problem:

"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header."

Could you double check that user is an API enabled user and you pass the API key in the Authorization header?

**Comment by carnak** [comment]
Hello - Many thanks for your reply, as that was exactly my problem, i.e., I was using the wrong API key, which I had copied from my previous instance, when building out this instance.  Thanks very much - MISP and M2M rocks!!!

Best Regards,
Alan
